version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - vendor-store:/var/www/laravel/vendor
      - node_modules-store:/var/www/laravel/node_modules
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php-fpm-socket:/var/run/php-fpm

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 13306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

volumes:
  db-store:
  php-fpm-socket:
  vendor-store:
  node_modules-store:
